//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.19 at 12:28:45 AM AEST 
//


package au.org.aodn.thredds.xml.catalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="datasetNameMatchPattern" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="datasetPathMatchPattern" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="startTimeSubstitutionPattern" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "addTimeCoverage")
public class AddTimeCoverage {

    @XmlAttribute(name = "datasetNameMatchPattern")
    protected String datasetNameMatchPattern;
    @XmlAttribute(name = "datasetPathMatchPattern")
    protected String datasetPathMatchPattern;
    @XmlAttribute(name = "startTimeSubstitutionPattern")
    protected String startTimeSubstitutionPattern;
    @XmlAttribute(name = "duration")
    protected String duration;

    /**
     * Gets the value of the datasetNameMatchPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetNameMatchPattern() {
        return datasetNameMatchPattern;
    }

    /**
     * Sets the value of the datasetNameMatchPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetNameMatchPattern(String value) {
        this.datasetNameMatchPattern = value;
    }

    /**
     * Gets the value of the datasetPathMatchPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetPathMatchPattern() {
        return datasetPathMatchPattern;
    }

    /**
     * Sets the value of the datasetPathMatchPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetPathMatchPattern(String value) {
        this.datasetPathMatchPattern = value;
    }

    /**
     * Gets the value of the startTimeSubstitutionPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTimeSubstitutionPattern() {
        return startTimeSubstitutionPattern;
    }

    /**
     * Sets the value of the startTimeSubstitutionPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTimeSubstitutionPattern(String value) {
        this.startTimeSubstitutionPattern = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

}
