//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.17 at 10:50:51 PM AEST 
//


package au.org.aodn.thredds.xml.catalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}DatasetType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}fmrcInventory" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}addTimeCoverage" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="runsOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fmrcInventory",
    "addTimeCoverage"
})
public class DatasetFmrc
    extends DatasetType
{

    protected FmrcInventory fmrcInventory;
    protected AddTimeCoverage addTimeCoverage;
    @XmlAttribute(name = "path", required = true)
    protected String path;
    @XmlAttribute(name = "runsOnly")
    protected Boolean runsOnly;

    /**
     * Gets the value of the fmrcInventory property.
     * 
     * @return
     *     possible object is
     *     {@link FmrcInventory }
     *     
     */
    public FmrcInventory getFmrcInventory() {
        return fmrcInventory;
    }

    /**
     * Sets the value of the fmrcInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FmrcInventory }
     *     
     */
    public void setFmrcInventory(FmrcInventory value) {
        this.fmrcInventory = value;
    }

    /**
     * Gets the value of the addTimeCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link AddTimeCoverage }
     *     
     */
    public AddTimeCoverage getAddTimeCoverage() {
        return addTimeCoverage;
    }

    /**
     * Sets the value of the addTimeCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddTimeCoverage }
     *     
     */
    public void setAddTimeCoverage(AddTimeCoverage value) {
        this.addTimeCoverage = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the runsOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRunsOnly() {
        return runsOnly;
    }

    /**
     * Sets the value of the runsOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunsOnly(Boolean value) {
        this.runsOnly = value;
    }

}
