//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.22 at 04:27:21 PM AEST 
//


package au.org.aodn.thredds.xml.catalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}DatasetType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="crawlableDatasetImpl" type="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}UserImplType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}filter" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}addID" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}namer" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}sort" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}addLatest" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}addProxies" minOccurs="0"/&gt;
 *         &lt;element name="addDatasetSize" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}addTimeCoverage" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="location" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dirLocation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="filter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="addDatasetSize" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="addLatest" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="addId" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "crawlableDatasetImpl",
    "filter",
    "addID",
    "namer",
    "sort",
    "addLatest",
    "addProxies",
    "addDatasetSize",
    "addTimeCoverage"
})
public class DatasetScan
    extends DatasetType
{

    protected UserImplType crawlableDatasetImpl;
    protected Filter filter;
    protected AddID addID;
    protected Namer namer;
    protected Sort sort;
    protected AddLatest addLatest;
    protected AddProxies addProxies;
    protected Object addDatasetSize;
    protected AddTimeCoverage addTimeCoverage;
    @XmlAttribute(name = "path", required = true)
    protected String path;
    @XmlAttribute(name = "location")
    protected String location;
    @XmlAttribute(name = "dirLocation")
    protected String dirLocation;
    @XmlAttribute(name = "filter")
    protected String filterAttribute;
    @XmlAttribute(name = "addDatasetSize")
    protected Boolean addDatasetSizeAttribute;
    @XmlAttribute(name = "addLatest")
    protected Boolean addLatestAttribute;
    @XmlAttribute(name = "addId")
    protected Boolean addId;

    /**
     * Gets the value of the crawlableDatasetImpl property.
     * 
     * @return
     *     possible object is
     *     {@link UserImplType }
     *     
     */
    public UserImplType getCrawlableDatasetImpl() {
        return crawlableDatasetImpl;
    }

    /**
     * Sets the value of the crawlableDatasetImpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserImplType }
     *     
     */
    public void setCrawlableDatasetImpl(UserImplType value) {
        this.crawlableDatasetImpl = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link Filter }
     *     
     */
    public Filter getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filter }
     *     
     */
    public void setFilter(Filter value) {
        this.filter = value;
    }

    /**
     * Gets the value of the addID property.
     * 
     * @return
     *     possible object is
     *     {@link AddID }
     *     
     */
    public AddID getAddID() {
        return addID;
    }

    /**
     * Sets the value of the addID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddID }
     *     
     */
    public void setAddID(AddID value) {
        this.addID = value;
    }

    /**
     * Gets the value of the namer property.
     * 
     * @return
     *     possible object is
     *     {@link Namer }
     *     
     */
    public Namer getNamer() {
        return namer;
    }

    /**
     * Sets the value of the namer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Namer }
     *     
     */
    public void setNamer(Namer value) {
        this.namer = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link Sort }
     *     
     */
    public Sort getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sort }
     *     
     */
    public void setSort(Sort value) {
        this.sort = value;
    }

    /**
     * Gets the value of the addLatest property.
     * 
     * @return
     *     possible object is
     *     {@link AddLatest }
     *     
     */
    public AddLatest getAddLatest() {
        return addLatest;
    }

    /**
     * Sets the value of the addLatest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddLatest }
     *     
     */
    public void setAddLatest(AddLatest value) {
        this.addLatest = value;
    }

    /**
     * Gets the value of the addProxies property.
     * 
     * @return
     *     possible object is
     *     {@link AddProxies }
     *     
     */
    public AddProxies getAddProxies() {
        return addProxies;
    }

    /**
     * Sets the value of the addProxies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddProxies }
     *     
     */
    public void setAddProxies(AddProxies value) {
        this.addProxies = value;
    }

    /**
     * Gets the value of the addDatasetSize property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddDatasetSize() {
        return addDatasetSize;
    }

    /**
     * Sets the value of the addDatasetSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddDatasetSize(Object value) {
        this.addDatasetSize = value;
    }

    /**
     * Gets the value of the addTimeCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link AddTimeCoverage }
     *     
     */
    public AddTimeCoverage getAddTimeCoverage() {
        return addTimeCoverage;
    }

    /**
     * Sets the value of the addTimeCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddTimeCoverage }
     *     
     */
    public void setAddTimeCoverage(AddTimeCoverage value) {
        this.addTimeCoverage = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the dirLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirLocation() {
        return dirLocation;
    }

    /**
     * Sets the value of the dirLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirLocation(String value) {
        this.dirLocation = value;
    }

    /**
     * Gets the value of the filterAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterAttribute() {
        return filterAttribute;
    }

    /**
     * Sets the value of the filterAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterAttribute(String value) {
        this.filterAttribute = value;
    }

    /**
     * Gets the value of the addDatasetSizeAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddDatasetSizeAttribute() {
        return addDatasetSizeAttribute;
    }

    /**
     * Sets the value of the addDatasetSizeAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddDatasetSizeAttribute(Boolean value) {
        this.addDatasetSizeAttribute = value;
    }

    /**
     * Gets the value of the addLatestAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddLatestAttribute() {
        return addLatestAttribute;
    }

    /**
     * Sets the value of the addLatestAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddLatestAttribute(Boolean value) {
        this.addLatestAttribute = value;
    }

    /**
     * Gets the value of the addId property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddId() {
        return addId;
    }

    /**
     * Sets the value of the addId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddId(Boolean value) {
        this.addId = value;
    }

}
