//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.22 at 04:27:21 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.org.aodn.thredds.xml.catalog;
