//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.22 at 04:27:21 PM AEST 
//


package au.org.aodn.thredds.xml.catalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import au.org.aodn.thredds.xml.ncml.Netcdf;


/**
 * <p>Java class for protoDatasetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="protoDatasetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2}netcdf" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="choice" type="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}protoChoices" /&gt;
 *       &lt;attribute name="change" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="param" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protoDatasetType", propOrder = {
    "netcdf"
})
public class ProtoDatasetType {

    @XmlElement(namespace = "http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2")
    protected Netcdf netcdf;
    @XmlAttribute(name = "choice")
    protected String choice;
    @XmlAttribute(name = "change")
    protected String change;
    @XmlAttribute(name = "param")
    protected String param;

    /**
     * Gets the value of the netcdf property.
     * 
     * @return
     *     possible object is
     *     {@link Netcdf }
     *     
     */
    public Netcdf getNetcdf() {
        return netcdf;
    }

    /**
     * Sets the value of the netcdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Netcdf }
     *     
     */
    public void setNetcdf(Netcdf value) {
        this.netcdf = value;
    }

    /**
     * Gets the value of the choice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoice() {
        return choice;
    }

    /**
     * Sets the value of the choice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoice(String value) {
        this.choice = value;
    }

    /**
     * Gets the value of the change property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChange() {
        return change;
    }

    /**
     * Sets the value of the change property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChange(String value) {
        this.change = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam(String value) {
        this.param = value;
    }

}
