//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.22 at 04:27:21 PM AEST 
//


package au.org.aodn.thredds.xml.ncml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.org.aodn.thredds.xml.ncml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.org.aodn.thredds.xml.ncml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnumTypedef }
     * 
     */
    public EnumTypedef createEnumTypedef() {
        return new EnumTypedef();
    }

    /**
     * Create an instance of {@link Aggregation }
     * 
     */
    public Aggregation createAggregation() {
        return new Aggregation();
    }

    /**
     * Create an instance of {@link Netcdf }
     * 
     */
    public Netcdf createNetcdf() {
        return new Netcdf();
    }

    /**
     * Create an instance of {@link EnumTypedef.Enum }
     * 
     */
    public EnumTypedef.Enum createEnumTypedefEnum() {
        return new EnumTypedef.Enum();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Values }
     * 
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link LogicalSection }
     * 
     */
    public LogicalSection createLogicalSection() {
        return new LogicalSection();
    }

    /**
     * Create an instance of {@link LogicalSlice }
     * 
     */
    public LogicalSlice createLogicalSlice() {
        return new LogicalSlice();
    }

    /**
     * Create an instance of {@link LogicalReduce }
     * 
     */
    public LogicalReduce createLogicalReduce() {
        return new LogicalReduce();
    }

    /**
     * Create an instance of {@link Remove }
     * 
     */
    public Remove createRemove() {
        return new Remove();
    }

    /**
     * Create an instance of {@link Aggregation.VariableAgg }
     * 
     */
    public Aggregation.VariableAgg createAggregationVariableAgg() {
        return new Aggregation.VariableAgg();
    }

    /**
     * Create an instance of {@link PromoteGlobalAttribute }
     * 
     */
    public PromoteGlobalAttribute createPromoteGlobalAttribute() {
        return new PromoteGlobalAttribute();
    }

    /**
     * Create an instance of {@link CacheVariable }
     * 
     */
    public CacheVariable createCacheVariable() {
        return new CacheVariable();
    }

    /**
     * Create an instance of {@link Aggregation.Scan }
     * 
     */
    public Aggregation.Scan createAggregationScan() {
        return new Aggregation.Scan();
    }

    /**
     * Create an instance of {@link Aggregation.ScanFmrc }
     * 
     */
    public Aggregation.ScanFmrc createAggregationScanFmrc() {
        return new Aggregation.ScanFmrc();
    }

}
